%Program to perform a discrete fourier transform and plot its magnitude and
%phase spectra, and then perform the inverse DFT.

close all; %close open figures and windows generated by running MATLAB code
clear all; %clear the workspace
clc;       %clear the command window

N = 128;        %No. of complex no.s
Fs= 8000;       %Sampling frequency
X = zeros(128); %Initialising variable of DFT
Ts= 1/Fs;       %Sampling time

%Discrete fourier transform
for k = 1:1:128      %No. of samples
    for n = 0:1:N-1  %Time index
     X(k)=X(k)+(cos(2000*pi*n*Ts)+cos(800*pi*n*Ts))*exp(-j*2*pi*(k-1)*n/N);
    end;
end;
X1 = fftshift(abs(X));  %shift the fft to center of maximum amplitude
f  = linspace(-Fs/2,Fs/2,N); %x axis symmetric around central frequency

%magnitude plot of DFT
figure(1)           %New figure window
stem(f,X1);         %Discrete plot
xlabel('k');        %Label of x axis
ylabel('X(k)');     %Label of y axis
title('magnitude plot of DFT 14UEC109');    %Title of plot

%phase plot of DFT
figure(2)           %New figure window
stem(f,fftshift(angle(X)));%Discrete plot
xlabel('k');    %Label of x axis
ylabel('\angle X(k)');  %Label of y axis
title('phase plot of DFT 14UEC109');    %Title of plot

%Inverse Discrete Fourier Transform
x1 = zeros(128); %initialising variable of IDFT signal
for n = 1:1:N    %time index
    for k = 1:1:128  %no. of samples
     x1(n)=x1(n)+(X(k)*exp(j*2*pi*(k-1)*(n-1)/N))/N; %IDFT
    end;
end;

k = 1:1:128;     %No. of samples
x0 = cos(2000*pi*k*Ts)+cos(800*pi*k*Ts);  %original signal

%IDFT PLOT
figure          %New figure window
subplot(2,1,1) %Plotted in first section of 2x1 figure
plot(k,x1);     %continuous plot
xlabel('k');    %Label of x axis
ylabel('x1(k)'); %Label of y axis
title('signal obtained from IDFT,14UEC109');    %Title of plot
hold on         %To hold the current plot in the figure window

%Plot of original signal
subplot(2,1,2)  %Plotted in second section of 2x1 figure
plot(k,x0);     %continuous plot
xlabel('k');     %Label of x axis
ylabel('x0(k)');  %Label of y axis
title('original signal,14UEC109');  %Title of plot
