%Take a speech signal and plot the magnitude and phase spectra.
close all; %close open figures and windows generated by running MATLAB code
clear all; %clear the workspace
clc;       %clear the command window

[Y, Fs]=audioread('cleanspeech_voice_8kHz.wav');

N = 128;        %No. of complex no.s
Fs= 8000;       %Sampling frequency
X = zeros(128); %Initialising variable of DFT of audio signal
Ts= 1/Fs;       %Sampling time

%Discrete fourier transform
for k = 1:1:128      %No. of samples
    for n = 0:1:N-1  %Time index
     X(k)=X(k)+Y((n+1))*exp(-j*2*pi*(k-1)*n/N);
    end;
end;
X1 = fftshift(abs(X));  %shift the fft to center of maximum amplitude
f  = linspace(-Fs/2,Fs/2,N); %x axis symmetric around central frequency

%magnitude plot of DFT of audio signal
figure(1)           %New figure window
stem(f,X1);         %Discrete plot
xlabel('k');        %Label of x axis
ylabel('X(k)');     %Label of y axis
title('magnitude plot of DFT of audio signal 14UEC109');    %Title of plot

%phase plot of DFT of audio signal
figure(2)           %New figure window
stem(f,fftshift(angle(X)));%Discrete plot
xlabel('k');    %Label of x axis
ylabel('\angle X(k)');  %Label of y axis
title('phase plot of DFT of audio signal 14UEC109');    %Title of plot
